name: common-windows-x86-64

on:
  #push:
  #  branches: [ master ]
  #  paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md]
  pull_request:
    branches: [ master ]
    paths-ignore: ['.**', 'docker/**', 'docs/**', 'samples/**', README.md,
                   'include/ppl/nn/engines/cuda/**', 'src/ppl/nn/engines/cuda/**']
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: [self-hosted, x64, win64]

    steps:
      - name: Create Checkout Directory
        run: |
          cd ../../ ; ./make_pplnn_dir.ps1 ${{ github.run_id }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.run_id }}

      - name: Build
        run: |
          cd ../../ ; ./build_pplnn.ps1 ${{ github.run_id }} x86_64

      - name: clean
        if: ${{ always() }}
        run: |
          cd ../../ ; ./clean_pplnn.ps1 ${{ github.run_id }} x86_64
